### ISSUE TITLE
[Bug]: Missing crafting recipes for Factory Blocks

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-10#1031]
### Possible Fixes

Yes

### Modpack Version

1.16

### What happened?

Crafting recipes for the Factory Blocks mod seems to be missing after upgrading my server from 1.15 to 1.16.
Can no longer craft the base "Dotted Rusty Plate" and can no longer use the Chipped Mason Workbench to create the other blocks.

**Comment by AdrianGamingDE** [comment]
Can confirm. Also if you're trying break the factory block with a pickaxe it takes ages after the update.

**Comment by DaddyLongspoon** [comment]
thanks, im here to file same bug report.
If you have some factory blocks in storage somewhere you can no longer put them to the chisel to change to another one.
And if you patiently wait thru the mining fatigue to break one, it drops nothing, its gone.

**Comment by welch3694** [comment]
Came to report this as well, can't craft them in 1.16.

**Comment by Trinknix** [comment]
+1 for every stated issue.

**Comment by Cebio** [comment]
ok so im not the only one thanks for publishing the issue

**Comment by AdrianGamingDE** [comment]
Update for 1.17:

- recipe for the regular factory blocks is back
- breaking factory blocks still takes ages
- the mason table still doesn't allow you to change appearance

**Comment by Cebio** [comment]
Also simple iron block is not craftable. Is it a chisel bug then?

**Comment by dorner-dev** [comment]
Loaded up a test world in 1.17.
- Can confirm the crafting recipe is back
- Chipped and Rechiseled cannot change the base block, however Chisel Reborn can
![image](https://github.com/user-attachments/assets/1e8311e2-216f-495f-96bd-7eeba06fc8b9)

- Breaking the block still takes ages and does not drop anything after completion, might be that the configured tool to break the block (pickaxe) is not set properly?

Here's what Jade shows for the factory blocks, compared to any "non-broken" mineable block,
![image](https://github.com/user-attachments/assets/c87c638d-9bc9-480f-a06c-63b338dffad2)
![image](https://github.com/user-attachments/assets/151354ce-e2bb-4bea-b577-fdd3614ac6c9)

**Comment by dorner-dev** [comment]
All issues seems to have been fixed in 1.18.
- Block is now breaking properly with a pickaxe
![Screenshot 2024-11-12 074346](https://github.com/user-attachments/assets/649a2e07-c7d0-40a0-9d92-2a4dc3f3ff14)
- Factory Blocks can now be changed using the Chipped Mason Table and Chisel as well as the other Chisel
![Screenshot 2024-11-12 074439](https://github.com/user-attachments/assets/88c83dc0-971f-4cd8-a3b6-9c48335f0b17)
![Screenshot 2024-11-12 074451](https://github.com/user-attachments/assets/c2141cbc-6a8a-4df1-8604-7ccde6f4bb18)
![Screenshot 2024-11-12 074504](https://github.com/user-attachments/assets/1b8d4130-61bc-44dc-946e-7704ca8c96c5)

Thanks for the quick fix guys :)

**Comment by Diagonet** [comment]
Factory blocks are no longer able to be changed by rechiseled chisel or the create one, only chisel reborn I think
