### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Hallunixating** [AllTheMods/ATM-10#123]
### Possible Fixes

Yes

### Modpack Version

ATM 10 0.16

### What happened?

Mod does not load, gives me Exit Code 1 when loading using CurseForge, crashes when using AT Launcher. Here is crash log, I have enough ram allocated and I've no idea why it won't let me play.

### Crash Log

https://paste.atlauncher.com/view/07c7b667-a07c-4a42-8459-438c522c1e0f

**Comment by Ratsliart** [comment]
Seconding this report, can't launch ATM 10 0.16 on FTB Launcher either. Gets through pre-start, validation  and then crashes immediately after this warning "OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended". No issues for me on ATM8 or 9.
