### ISSUE TITLE
[Bug]: Infernal Mods promoting wilden chimera to almost unkillable hyper boss

### ISSUE THREAD

**Issue by g33sys** [AllTheMods/ATM-10#1299]
### Possible Fixes

Yes

### Modpack Version

1.24

### What happened?

Summoning a Wilden Chimera resulted in it being invisible, armored, webbing, teleporting, withered, poisoned and a couple of additional affixes. It almost got lost in the mining dimension (public server). Similar nonsense happened with a friends wither builder. At least bosses should be black listed for that mod. This completely breaks possible early to mid-game progression for ars noveau. In addition, Infernal Mobs makes the other dungeons unsurivable without using reliquiary to become invisible to every mob. This can't be an intended play style.

**Comment by dl-o-lb** [comment]
![Infernal Promoted Wilden_Boss All The Mods 10-2 1](https://github.com/user-attachments/assets/f0bb45c7-8aed-4e92-abe1-756e22520b60)


Can confirm that this Bug is still happening in All The Mods 10 version 2.1, I've updated and it appears to still exist as a boss in version 2.8. This issue may still be occurring on newer versions
