### ISSUE TITLE
[Bug]: Applied Energistics 2 Autocrafting Stalling

### ISSUE THREAD

**Issue by JamesSSmith** [AllTheMods/ATM-10#1310]
### Possible Fixes

Yes

### Modpack Version

1.26

### What happened?

When trying to craft certain recipes, the items just sit in the modular assembler, and do not craft, currently I have found a few recipes that this happens for listed and shown below, any more found will be added to the list. To clarify I have tried these in single player and they do work on there, so this seems like a multiplayer issue. These also work as manual crafts. All other crafts I have in there are working without issue for now, not sure if the higher up cells and providers as it hasn't got that far.

Current Setup
Bisect Hosting Server
8 GB RAM

Extended Pattern Providers - Yellow Ones
Extended Modular Assemblers

Recipes
Aureal Bottle - https://imgur.com/a/0H6L1W2
Elite Induction Cell/Provider - https://imgur.com/a/HiIKzHm
Basic Energy Cell - https://imgur.com/a/lmHoFxA

**Comment by LordCorellon** [comment]
Have you tried turning off the "Substitutions" check boxes, I went and unchecked all the checkbox's (both substitution and use fluids directly) from the pattern and saved it again and that fixed the issues for me.

So yes now I have to ensure I have Oak planks instead of any planks but it doesn't stall for me anymore, this is more prone to happen with Mechanism and Modern Industrialization recipes.

I've also had it happen with other recipes but that tends to be a result of extremely large production jobs (Such as a quantum upgrade from scratch, sometimes it just "Forgets" where it is in the job and I have to cancel and restart

**Comment by JamesSSmith** [comment]
> Have you tried turning off the "Substitutions" check boxes, I went and unchecked all the checkbox's (both substitution and use fluids directly) from the pattern and saved it again and that fixed the issues for me. Happens 100% of the time on energy cells and induction cells if I don't turn it off.
> 
> So yes now I have to ensure I have Oak planks instead of any planks but it doesn't stall for me anymore, this is more prone to happen with Mechanism and Modern Industrialization recipes.
> 
> I've also had it happen with other recipes but that tends to be a result of extremely large production jobs (Such as a quantum upgrade from scratch, sometimes it just "Forgets" where it is in the job and I have to cancel and restart

Heres me thinking i had covered all my bases, but this worked like a dream, thank you very much dude.!

**Comment by JamesSSmith** [comment]
Fixed by just turning of substitutes for the patterns
