### ISSUE TITLE
[Crash]: Error: java.lang.IllegalStateException: Mod 'architectury' is not available!

### ISSUE THREAD

**Issue by KusanagiRyu** [AllTheMods/ATM-10#1392]
### Possible Fixes

No

### Modpack Version

2.3

### What happened?

Game crash when starting, showing above mentioned error.

### Crash Log

https://gist.github.com/KusanagiRyu/9288fcb7de17380bbaee54717bd5a057

### Latest.Log

https://gist.github.com/KusanagiRyu/c1738e22b6f5fb73249dfbc22fce61cd

**Comment by alekthefirst** [comment]
This has been an issue for a long time
https://github.com/architectury/architectury-api/issues/528
One person suggests that adding `-Duser.country=US -Duser.language=en` to your args might solve the issue. Due to this being so hard to reproduce i can not verify that this works
The usual go to solution has been to uninstall the game and the launcher completely, then reinstall.
Omega config has spend along time in radio silence about this, the issue was put on their github half a year ago
https://github.com/Draylar/omega-config/issues/26

**Comment by KusanagiRyu** [comment]
yeah, that's true. I had such issue with other modpack. Sad to say, the args solution doesn't work.

**Comment by alekthefirst** [comment]
Just marking as duplicate of https://github.com/AllTheMods/ATM-10/issues/130 for record keeping

**Comment by KDCheapCheap** [comment]
For Curseforge users, I managed to get it work by switching my Minecraft launcher to the Curseforge launcher. This requires linking your Microsoft to Curseforge but it worked for me :)
