### ISSUE TITLE
[Feature]: antiblocks removal rollback

### ISSUE THREAD

**Issue by Dorrivix** [AllTheMods/ATM-10#1568]
### Feature Details

Luminax is not a proper replacement for antiblocks. I believe there is either room for both, or if not, swapping back to Antiblocks would be preferrable.

Antiblocks are shadeless, meaning the face does not get darker on the sides or bottom. luminax blocks get darker as you view them from the sides or especially the bottom. in certain situations, you may want a dephless void, such as for a display,

**Comment by TheBedrockMaster** [comment]
#2 for mod suggestions, this isn’t planned.

**Comment by HexiDave** [comment]
This should probably be re-visited as AntiBlocks have a very different look than Luminax. My server is effectively pinned to version 2.11 because updating would wreck a number of large builds. I could understand if there was some kind of bug or issue, but I can't find any reason for this change to a largely unused and untested new mod. 

Who asked for this change? Why wouldn't you make room for both in the pack if they operate differently?

AntiBlocks (2.11)
![AntiBlocks](https://github.com/user-attachments/assets/d7e40b43-0f4a-46bc-951d-a71557eacd40)

Luminax (2.12+)
![Luminax](https://github.com/user-attachments/assets/729b6bb8-0bd7-4d1b-9919-5d085b572dfd)
