### ISSUE TITLE
[Bug]: Setting menu in copy-paste gadget is blurred out.

### ISSUE THREAD

**Issue by lvv-sess** [AllTheMods/ATM-10#254]
### Possible Fixes

No

### Modpack Version

0.31

### What happened?

If you use the settings button (after pulling up the radial menu, it's the one with the pencil icon), the screen blurs as if opening up a menu but nothing appears. I was told this also hapens with SFM and Waystones menu. I tried tracing it back, it worked in 0.29 then stopped working 0.30 onwards.

I also tried downgrading EMI (since this is what stood out in the changelog for 0.30) as well as downgrading building gadgets mod, but it didn't work.
![Untitled](https://github.com/user-attachments/assets/152a5795-ad19-49c4-a8a6-fa2922e3e617)

**Comment by lvv-sess** [comment]
Updated to 0.33, no difference. Menus in copy-paste gadget and renaming waystones still blurred out and inaccessible.

**Comment by Seegras** [comment]
Same with 0.34. 

Basically this makes the paste-modus of the copypaste gadget useless, since you can't really tell it exactly where you want the structure pasted. 

Also, you'll end up with a lot of "Untitled Waystones" since you also can't (re-)name them. 

Here's another screenshot
![2024-08-18_18 47 06](https://github.com/user-attachments/assets/2eda097b-20b1-4f98-832f-79a3905245d6)

**Comment by LordCorellon** [comment]
> Also, you'll end up with a lot of "Untitled Waystones" since you also can't (re-)name them (I'm pretty sure this is the same bug as #251).

If you type a name in while the screen is blurred it will still accept it and name the waystone, same applies for all the blurred menu's they are technically there and work if you know where the buttons are, what they do, etc you just can't see them.

There is some really weird conflict going on with the mods since I reported the issue with Iron's Spellbook since the same thing happends to the main menu if this specific list of mods is loaded:

Mods:
[✔] [1.21] SecurityCraft v1.9.10-beta7
[✔] appleskin-neoforge-mc1.21-3.0.5
[✔] architectury-13.0.6-neoforge
[✔] ars_nouveau-1.21.0-5.0.7-all
[✔] artifacts-neoforge-12.0.4
[✔] balm-neoforge-1.21-21.0.14-all
[✔] caelus-neoforge-7.0.0+1.21
[✔] cloth-config-15.0.128-neoforge
[✔] curios-neoforge-9.0.5+1.21.0
[✔] ExplorersCompass-1.21-3.0.2-neoforge
[✔] FarmersDelight-1.21-1.2.4
[✔] flickerfix-1.21.0
[✔] FramedBlocks-10.1.3
[✔] geckolib-neoforge-1.21-4.5.8
[✔] irons_spellbooks-1.21-3.4.1-all
[✔] jei-1.21-neoforge-19.8.1.98
[✔] journeymap-neoforge-1.21-6.0.0-beta.18
[✔] justdirethings-0.11.21
[✔] mahoutsukai-1.21.0-v1.35.11
[✔] Mekanism-1.21-10.6.7.54
[✔] Modern-Industrialization-2.2.16-beta
[✔] modonomicon-1.21-neoforge-1.98.0
[✔] NaturesCompass-1.21-3.0.3-neoforge
[✔] occultism-1.21-neoforge-1.146.1
[✔] pneumaticcraft-repressurized-8.0.2+mc1.21
[✔] SmartBrainLib-neoforge-1.21-1.14.5

If you take any of those mods out the main menu works, but if those mods are all present the main menu gets the same blurred  invisibility treatment, I suspect it's the same thing happening with these menu's.

If you remove Irons Spellbook I think there is a good chance the other menu's will work again (I don't think it's an actual issue with Iron's spellbook since it works alone and with other mods, it's something to do with specific combination of mods of which iron's spellbook is one of them (and it was added in .30 which is when it stopped working for you)

**Comment by recon88** [comment]
See:
https://github.com/TwelveIterationMods/Waystones/issues/889#issuecomment-2328795114
