### ISSUE TITLE
[Bug]: Iron Jetpacks: none of the coils have crafting recipe

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#310]
### Possible Fixes

Yes

### Modpack Version

10.0.38

### What happened?

Cannot get started on this mod because none of the coils ( ironjetpacks:basic_coil , ironjetpacks:advanced_coil , ironjetpacks:elite_coil , ironjetpacks:ultimate_coil ) can be crafted.

**Comment by The1stVoidRunner** [comment]
Neither does the Leather Strap. (Ironjetpacks:strap)

**Comment by LordCorellon** [comment]
Even if you add the recipes for the coils and the straps the jetpack recipes are still broken.

Aside from the wood jetpack every backpack needs the previous one to craft the next tier, except that it will only craft the current jetpack (wasting all the components).

IE:  If you craft the stone jetpack with 4 stone, 1 stone cell, 1 wood jetpack and 2 stone thrusters instead of crafting a stone jetpack it will only craft a wood jetpack.

**Comment by LordCorellon** [comment]
I made a KubeJS file that will fix the issue, I'm not very good with KubeJS and more so since the changes from 1.21 so I couldn't figure out how to remove the old broken recipes (since the jetpacks don't upgrade, Wood->Stone still gives Wood jetpack back).
 
[Iron Jetpacks.zip](https://github.com/user-attachments/files/16738474/Iron.Jetpacks.zip)

**Comment by RIExJonny** [comment]
i think i posted mine in the wrong spot as i posted it on iron jetpack page but as i commented over there LordCorellon thanks for the file but its something that the allthemods would have to add in themselfs on a update. for us

**Comment by LordCorellon** [comment]
You can copy the script into the kubejs\server_scripts\mods folder and it will work until either the mod or the ATM team can patch the issue, it at least got my personal family server running with jetpacks

**Comment by DeadSoul2002** [comment]
is this a normal. i had iron jetpack as soon as i was atacked it broke.
