### ISSUE TITLE
[Bug]: XYcraft blocks Texture bug

### ISSUE THREAD

**Issue by Akarnie73** [AllTheMods/ATM-10#480]
### Possible Fixes

No

### Modpack Version

10-0.50

### What happened?

i want to build with the XyCraft Override Deepslate Bricks versions but there is a very anoying texture bug with all the versions of everykind of it

**Comment by alekthefirst** [comment]
I will need more information on what this alleged texture bug is supposed to be, images preferred
They otherwise look fine to me
![image](https://github.com/user-attachments/assets/fb35d6df-2065-49ca-8710-62ddc7337ea6)
Given the age of the issue i am closing as stale, until information shows up that says this is still an issue.
