### ISSUE TITLE
[Bug]: Mystical Agriculture mystical enlightenment unobtainable

### ISSUE THREAD

**Issue by georgeribeiro** [AllTheMods/ATM-10#482]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

Mystical Enlightenment enchantmenet is unobtainable, because mystical agriculture enchanter not working, librarian villagers not have mystical enlightenment and not obtainable in enchantment table.

![2024-09-11_18 13 14](https://github.com/user-attachments/assets/8b653ff8-e525-400f-8eaf-67faeda4e347)

**Comment by alekthefirst** [comment]
Issue was supposedly fixed in https://github.com/BlakeBr0/MysticalAgriculture/issues/710 with commit https://github.com/BlakeBr0/MysticalAgriculture/commit/88e0ad3f72ac99a86014110a3f3edd7f099e8806 released with MA 8.0.5, now superseded by 8.0.6, which isn't in atm10 yet.
Although even if you could get the enchant rumors are it doesn't work to get the dust, and i have seen no changelogs regarding that issue

**Comment by evelynisthebest** [comment]
worked fine for me to get dust with books obtained via creative. I think by default only the dragon not the wither is enabled in the config. 

> Issue was supposedly fixed in [BlakeBr0/MysticalAgriculture#710](https://github.com/BlakeBr0/MysticalAgriculture/issues/710) with commit [BlakeBr0/MysticalAgriculture@88e0ad3](https://github.com/BlakeBr0/MysticalAgriculture/commit/88e0ad3f72ac99a86014110a3f3edd7f099e8806) released with MA 8.0.5, now superseded by 8.0.6, which isn't in atm10 yet. Although even if you could get the enchant rumors are it doesn't work to get the dust, and i have seen no changelogs regarding that issue

**Comment by alekthefirst** [comment]
>  I think by default only the dragon not the wither is enabled in the config.
i wasn't aware of that change, thank you
