### ISSUE TITLE
[Bug]: Croptopia Trees - unable to harvest with right click

### ISSUE THREAD

**Issue by ryocryte** [AllTheMods/ATM-10#520]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

Right-clicking the leaves in which crops are growing on Croptopia trees does not harvest them. Tried with bare hand, sword and shears.

**Comment by elowanut** [comment]
This is still an issue on the latest (0.56) version. Right click harvesting doesn't work with any Croptopia crops, in the ground, or in trees. Obviously it's a bigger issue with the trees, since you have to break the fruiting blocks to get the crops, if you can't right click harvest. That said, this is a Croptopia issue, see ExcessiveAmountsOfZombies/Croptopia/issues/640

**Comment by gkr0013** [comment]
Hello,

To "solve" the problem, you can install the 'RightClickHarvest' mod (and disable the need for a hoe).
