### ISSUE TITLE
Java gc creating lag spikes

### ISSUE THREAD

**Issue by PapaPumpkinnn** [AllTheMods/ATM-10#580]
i dont know what  to do i allocated 10gb of ram to atm10 and my memory usage keeps increasing and then suddently deecreasing causing lag i have tried to up my ram to 16gb and still have this issue even when i put only 8 i even tried with 5 and still nothing i need help
my pc has 32gb of ram and i have an 3080 i shouldnt have these issues if anyone knows something pls help
i really love atm modpacks so i really want to play it

**Comment by HistoriaGamer** [comment]
Yeah I'm having this issue as well. been having this issue on ANY 1.21 pack. Not sure what could be causing it. It almost feels like a mod is causing a Memory leak. I also have a 3080.

**Comment by leagris** [comment]
Memory leak on player death in ATM10 1.17a is so dramatic that it requires a full game restart to clear.

**Comment by alekthefirst** [comment]
> i dont know what to do i allocated 10gb of ram to atm10 and my memory usage keeps increasing and then suddently deecreasing causing lag

This is normal java garbage collection, the bane of all minecraft players. With ATM10 and other 1.21 packs, having overwolf on the computer has introduced a second source of similar stuttering. Removing overwolf would be the only resolution there. For normal java gc, since you have ram to spare, we recommend using the ZGC arguments instead
`-XX:+UseZGC -XX:+ZGenerational -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+PerfDisableSharedMem -XX:+UseDynamicNumberOfGCThreads`

**Comment by alekthefirst** [comment]
For @HistoriaGamer and @leagris 
We are aware of several memory leaks and are working to resolve them with their individual mod authors
https://github.com/AllTheMods/ATM-10/issues/292 will have status updates on them
