### ISSUE TITLE
[Crash]: Passing the cursor over the objects from minecolonies crashes minecraft

### ISSUE THREAD

**Issue by Holydaytab** [AllTheMods/ATM-10#594]
### Possible Fixes

Yes

### Modpack Version

Atm10-0.57

### What happened?

Passing the cursor over the objects from minecolonies crashes minecraft

### Crash Log

https://gist.github.com/Holydaytab/852fc67bc07c09e076992a9ed87e7022

**Comment by WesHay** [comment]
Same here, running the curser over minecolonies items in the JEI listing will crash my game too

**Comment by GarthF** [comment]
Havent tested all the items, but I found specifically the "Schematic Analyzer" causes an instant crash.

**Comment by DaRealDaDuwin** [comment]
Just adding on to what GarthF mentioned, it appears to be an issue specifically with the "Schematic Analyzer" when I cursor over it in the EMI search menu. I have not tested it with all the other mine colonies items but the issue with the schematic analyzer is repeatable and results in the game crashing everything time when attempted. 

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-09-25 10:20:42
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.getX()" because "pos" is null
	at TRANSFORMER/structurize@1.0.751-1.21.1-

**Comment by Raycoms** [comment]
Was fixed on minecolonies side
