### ISSUE TITLE
[Bug]: Fluorite Bee not producing when not using a feeding slab

### ISSUE THREAD

**Issue by plantasia124** [AllTheMods/ATM-10#611]
### Possible Fixes

Yes

### Modpack Version

.58

### What happened?

Making a fissile fuel setup and finished getting some fluorite bees, however they are not producing any combs. I used the time wand on it, changing beehives, replacing flowing block. Nothing worked until I placed it in a feeding slab.

**Comment by Ragelyna** [comment]
This is just caused by AllTheOres Fluorite Block doesnt have any block tags for productivebees:flower/fluorite . And in the pack only the Mekanism Fluroite Block has that tag but you can't craft it. If you know how to use kubejs just add that block tag to AllTheOres Fluorite Block and youre good to go.
