### ISSUE TITLE
Game stops for a second

### ISSUE THREAD

**Issue by TheEmpireSro** [AllTheMods/ATM-10#621]
Hello,

I have 38gb ram allocated and when I move the game has a 1 second lag spike. It´s not going up to the max allocated ram. it stays on like 10-12k ram. Can someone help me? It´s only in ATM 10. Every other pack looks fine. 

https://imgur.com/a/HIE7PgD

**Comment by Leon-JavaScript** [comment]
You may have too much ram allocated. The freeze happend when the garbage collector was clearing unneccessary data in your memory. Because you have so much ram allocated the garbage collector needs more time to clear the data your game doesnt need anymore. Try it with a bit less ram, maybe 10-12GB, so the garbage collector doesnt need to lookup that much data.

**Comment by Hamude99** [comment]
I've also been having this issue since I started playing, but I still get it at 12gb ram and sometimes it also says I need more ram when I launch, and when I try with 10gb it always says it ran out of memory.

**Comment by crowrvo** [comment]
Same thing for me, 10-12gb allocated and constants 1 second lag spike on a pc with 48gb ram in total, RTX 4060 and Ryzen 7 5700X

**Comment by kardi956** [comment]
I have exactly the same problem but I'm playing on notebook and don't know how to solve this issue by myself so I just wanted to ask somebody how to fix it.
(I'm using ASUS TUF GAMING A15) the game is running on 90 - 100 fps all the time but this bugs are like non-stop.
