### ISSUE TITLE
mineColonies problem.

### ISSUE THREAD

**Issue by jasminilu98** [AllTheMods/ATM-10#634]
normal lanterrn issue, shows as black/purple x in list, all MineColonies structures needs lantern to build above lvl 2. please fix this issue so we can use MineColonies as how it is intended

**Comment by LinniRM** [comment]
More information because I've been running into the same issue

The Minecolonies NPCs do not recognize vanilla lanterns as lanterns. When they need lanterns for a building upgrade you can fulfill their request if you have lanterns in your inventory, but the NPC will just put the lanterns on a shelf and then complain that they don't have lanterns. 
I suspect it has to do with another mod in the pack interfering with the lantern's item ID (I have tested the most recent version of Minecolonies by itself and it doesn't have the same issue.) because, as stated above, the lanterns item preview image appears as a missing texture error, both in the Minecolonies builder's item request list AND in the WAILA style pop-up when you point your cursor at a lantern.

The only work around I have found for now is to give the builder all the other supplies that they need then tell them to cancel the request for lanterns. This will force them to start building with what they have, but they won't be able to finish. I then go in and manually place the lanterns where they are supposed to go in the final build (you can use the Builder's goggles item to make this easier). Then eventually the NPCs AI will realize that they don't need lanterns anymore and they will finish the build.

**Comment by TobyD** [comment]
FWIW, you can manually place the lanterns, then ask the builder to ignore the lantern request. This seems to get them past the issue. It's tedious, but a workaround.

To figure out where to place them, use the builders wand to place a new version of the same building and set it to the level you are trying to build, then you can look around and see where they go.
