### ISSUE TITLE
[Crash]: Server hangs during startup 

### ISSUE THREAD

**Issue by natebc** [AllTheMods/ATM-10#643]
### Possible Fixes

Yes

### Modpack Version

0.60

### What happened?

Started server and shortly after loading the world it hangs with various backtraces and doesn't fully start up.

I tried this with my original world and with a freshly generated world. Linked in the gist is the run from a freshly generated world.

### Latest.Log

https://gist.github.com/natebc/9294f418e7a583e5d53561f8f779b611#file-latest-log-L3536

### Debug.Log

https://gist.github.com/natebc/f7d079da820a01d8e885613f3e72dd51

**Comment by alekthefirst** [comment]
Logs doesn't indicate anything about the server hanging. The recipe and minecolonies spam is normal. If anything i'd think this server was joinable (the server list in game doesn't properly ping the server because of another bug)
What is your server watchdog timeout set to? If it is hanging letting the watchdog crash the server will usually reveal what it is hanging on
