### ISSUE TITLE
[Bug]: Ars Additions Warp Nexus does not render stored warp locations correctly with or without shaders

### ISSUE THREAD

**Issue by VorpalSaber** [AllTheMods/ATM-10#670]
### Possible Fixes

Yes

### Modpack Version

0.60

### What happened?

Whatever sort of choosing wheel or matrix doesn't load with the blur effect but you can blindly click on the screen and get one of your saved locations randomly, so that's neat!
![2024-10-02_13 18 38](https://github.com/user-attachments/assets/0d79fa56-8e8e-47b2-8c4a-bb733a3a19a8)
![2024-10-02_13 19 02](https://github.com/user-attachments/assets/8f487128-7d85-4f87-af8e-de83459b4d8a)

**Comment by Jarva** [comment]
This is a known issue with multiple GUIs in 1.21, the fix is pinned in the atm10-general channel of the discord: https://discord.com/channels/254530689225981953/1236826820200894496/1280955541157449758

To summarize, you need to go to your accessibility settings and set menu background blur to off.
![image](https://github.com/user-attachments/assets/3a83b642-434c-4a20-a002-12d898979385)

**Comment by VorpalSaber** [comment]
Awesome thanks!
