### ISSUE TITLE
[Crash]: exit code 6 crash on the 0.61 version of the pack

### ISSUE THREAD

**Issue by Pcguy1000** [AllTheMods/ATM-10#687]
### Possible Fixes

Yes

### Modpack Version

0.61

### What happened?

I was trying to load up the pack and it crashed and the mine craft window didn't have the mods number listed in the bottom right on the title screen. It basally crashed while loading but only Minecraft loaded up and not the mods.

### Crash Log

https://gist.github.com/Pcguy1000/27d174d3588a6a5e2738361863893ffe

**Comment by alekthefirst** [comment]
Crashed in nvidia driver because it failed to load a library file
Would need this file to further diagnose `/home/mikejarreau/.var/app/org.polymc.PolyMC/data/PolyMC/instances/All the Mods 10 - ATM10/minecraft/hs_err_pid82.log`
Gives the age of the issue without further complaints, i'm closing it, and then it can be re opened if its still an issue
