### ISSUE TITLE
[Bug]: Dup all items

### ISSUE THREAD

**Issue by tavimxlseven** [AllTheMods/ATM-10#946]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

Dup of items

https://streamable.com/f69y8m

**Comment by DiggityMan420** [comment]
I'm confused can you give a example or ar written explanation i cant not seem to follow and repeat said dupe

**Comment by tavimxlseven** [comment]
I don't even know exactly how it works, but in practice, when you have an item in the integrated dynamics terminal and you press shift click to pull the crafted item, even if it doesn't exist, the items in the terminal are duplicated, as you can see in the video, when I click on the empty terminal, the diamond shards are duplicated.

**Comment by Nlcko** [comment]
I noticed a bug while crafting with the Storage Terminal: when I ran out of ingredients, the next click caused my remaining ingredients to disappear. This happened with all crafts. It seems that this issue might have appeared due to a recent fix. I was following the same process as you, and it had never happened before.

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/829
